name = "0xHivebrite"
license = "MIT"
description = "A theme for Hivebrite's engineering blog based on 0xDC.me theme."
homepage = "https://engineering.hivebrite.io"
tags = ["hivebrite", "engineering", "blog"]
features = ["technical", "blog"]
min_version = "0.91.0"

[author]
  name = "David Calvert"
  homepage = "https://0xdc.me"

# Authors of Hugo Clarity
original = [
  {name = "Chip Zoller", homepage = "https://neonmirrors.net"},
  {name = "Dan Weru", homepage = "https://github.com/onweru"},
  {name = "Ivan Boothe", homepage = "https://rootwork.org"}
]
